### ISSUE TITLE
could not run with coverage "rcc"

### ISSUE THREAD

**Issue by zofieLin** [GMELab/RV-EXCALIBER#5]
Hi, 

I am using RV-EXCALIBER for the association test and it runs well with `coverage "hcc"` but interrupted with  `coverage "rcc"` , coming with the errors I posted below.
I wonder if you could help to have a look at that? 
Thanks!

![image](https://user-images.githubusercontent.com/51777970/158397062-0490a9c1-3104-42c2-ab4a-edbc1347febc.png)

**Comment by rlali** [comment]
Hi @zofieLin,

Thank you for bringing this to my attention. I will identify the bug and let you know upon rectifying.

**Comment by rlali** [comment]
This issue has been fixed in the newest RV-EXCALIBER version.
