### ISSUE TITLE
Error with dataframe

### ISSUE THREAD

**Issue by OmicsS** [GMELab/RV-EXCALIBER#7]
Hi,

I am using RV-Excliber on an HPC cluster for an Exome analysis.
I used the scripts as described in the documentation and unfortunately I got the following error when using ./get_RVBurdenMatrix_gnomAD_rvexcaliber.clean.sh (step 2): "Error in `[.data.frame`(dfAll, , c(1: 13, 15, 14)) :
  undefined columns selected". 

I checked the error and this error appears in the R script "get_Varlist_rvexcaliber.R" (line ~ 670: dfAll <- dfAll[,c(1:13,15,14)])).

Information about my inputdata:

I generated plink files from my vcf, which consists many different variants over several chromosomes.
The input file is not split into chromosomes, so I used Step 1a normally like in the example:

 cd ${rvexcaliber_shell_scripts}
bash get_RVBurdenMatrix_internal_rvexcaliber.clean.sh /genetics/inData /genetics/outData MIGen_BioImage_ExS_QC 0.001,0.005 0.01 0.009,0.025 nfe rcc 10

Next I used Step2 like the example:

cd ${rvexcaliber_shell_scripts}
bash get_RVBurdenMatrix_gnomAD_rvexcaliber.clean.sh /genetics/outData MIGen_BioImage_ExS_QC 0.001,0.005 0.009,0.025 nfe rcc

I hope you can help me.

Kind regards

**Comment by rlali** [comment]
Hi @OmicsS,

Thank you for bringing this up. There was a formatting issue with the ``rcc`` gnomAD files. The issue has been fixed. Please download the newest version of RV-EXCALIBER with``git`` and let me know if you encounter any further issues.
